Separate ssm update operations of storage and app stack into steps. Modified index.html code and applincation-stack.yaml code to trigger the pipeline

diff --git a/.github/workflows/deploy-infra.yaml b/.github/workflows/deploy-infra.yaml
--- a/.github/workflows/deploy-infra.yaml
+++ b/.github/workflows/deploy-infra.yaml
@@ -61,75 +61,54 @@ jobs:
 
             STACK_NAME="${STACK}-stack"
 
-            STACK_EXISTS=$(aws cloudformation describe-stacks \
+            aws cloudformation deploy \
               --stack-name "$STACK_NAME" \
-              --region $AWS_REGION \
-              --query "Stacks[0].StackStatus" \
-              --output text 2>/dev/null || echo "NOT_EXIST")
+              --template-file "$TEMPLATE_FILE" \
+              --parameter-overrides file://"$PARAMS_FILE" \
+              --capabilities CAPABILITY_NAMED_IAM \
+              --region "$AWS_REGION"
 
-            if [[ "$STACK_EXISTS" == "NOT_EXIST" ]]; then
-              echo "Stack $STACK_NAME does not exist → creating"
-              aws cloudformation deploy \
-                --stack-name "$STACK_NAME" \
-                --template-file "$TEMPLATE_FILE" \
-                --parameter-overrides file://"$PARAMS_FILE" \
-                --capabilities CAPABILITY_NAMED_IAM \
-                --region "$AWS_REGION"
+      - name: Update storage ssm parameter
+        run: |
+          BUCKET_NAME=$(aws cloudformation describe-stacks \
+            --stack-name $STACK_NAME \
+            --query "Stacks[0].Outputs[?OutputKey=='OutputBktName'].OutputValue" \
+            --output text \
+            --region $AWS_REGION)
 
-              aws cloudformation wait stack-create-complete \
-                --stack-name "$STACK_NAME" \
-                --region "$AWS_REGION"
-              echo "$STACK_NAME created!!!"
-            else
-              echo "Stack $STACK_NAME exists → updating"
-              aws cloudformation deploy \
-                --stack-name "$STACK_NAME" \
-                --template-file "$TEMPLATE_FILE" \
-                --parameter-overrides file://"$PARAMS_FILE" \
-                --capabilities CAPABILITY_NAMED_IAM \
-                --region "$AWS_REGION"
+          if [ -z "$BUCKET_NAME" ]; then
+            echo "BucketName output missing"
+            exit 1
+          fi
 
-              aws cloudformation wait stack-update-complete \
-                --stack-name "$STACK_NAME" \
-                --region "$AWS_REGION"
-              echo "$STACK_NAME updated!!!"
-            fi
+          aws ssm put-parameter \
+            --name "${{ vars.SSM_BUCKET_PARAM }}" \
+            --value "$BUCKET_NAME" \
+            --type String \
+            --overwrite \
+            --region $AWS_REGION
+          echo "Stored $BUCKET_NAME in SSM"
 
-            if [[ "$STACK" == *"storage"* ]]; then
-              BUCKET_NAME=$(aws cloudformation describe-stacks \
-                --stack-name $STACK_NAME \
-                --query "Stacks[0].Outputs[?OutputKey=='OutputBktName'].OutputValue" \
-                --output text \
-                --region $AWS_REGION)
+      - name: Update app ssm parameter
+        run: |
+          ALB_DNS=$(aws cloudformation describe-stacks \
+            --stack-name $STACK-stack \
+            --query "Stacks[0].Outputs[?OutputKey=='ALBPublicDNS'].OutputValue" \
+            --output text \
+            --region $AWS_REGION)
 
-              aws ssm put-parameter \
-                --name "${{ vars.SSM_BUCKET_PARAM }}" \
-                --value "$BUCKET_NAME" \
-                --type String \
-                --overwrite \
-                --region $AWS_REGION
-              echo "Stored $BUCKET_NAME in SSM"
+          if [ -z "$ALB_DNS" ]; then
+            echo "ALB DNS output missing"
+            exit 1
+          fi
 
-            elif [[ "$STACK" == *"application"* ]]; then
-              ALB_DNS=$(aws cloudformation describe-stacks \
-                --stack-name $STACK-stack \
-                --query "Stacks[0].Outputs[?OutputKey=='ALBPublicDNS'].OutputValue" \
-                --output text \
-                --region $AWS_REGION)
-
-              # Store ALB DNS in SSM
-              aws ssm put-parameter \
-                --name "${{ vars.SSM_ALB_DNS_PARAM }}" \
-                --value "$ALB_DNS" \
-                --type String \
-                --overwrite \
-                --region $AWS_REGION
-              echo "Stored $ALB_DNS in SSM"
-
-            else
-              echo "No SSM parameters for $STACK-stack!!!"
-            fi
-          done
+          aws ssm put-parameter \
+            --name "${{ vars.SSM_ALB_DNS_PARAM }}" \
+            --value "$ALB_DNS" \
+            --type String \
+            --overwrite \
+            --region $AWS_REGION
+          echo "Stored $ALB_DNS in SSM"
 
       - name: Verify stack statuses
         run: |
